version: '2'
services:
  db:
    image: postgres:9.5
    ports:
      - '54321:5432'
  web:
    build: .
    image: dmemo
    env_file: .env.docker
    network_mode: host
    environment:
      DATABASE_URL: postgres://postgres@localhost:54321/dmemo_production
      RAILS_ENV: production
    volumes:
      - ./log/docker:/app/log
